image: maven:latest

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - mvn clean checkstyle:check

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/project-8-1.0.0.jar
