image: maven:latest

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - mvn clean checkstyle:check

build:
  stage: build
  script:
    - mvn package
    - ren target\project-8-1.0.0.jar Three-in-a-Row.jar
  artifacts:
    paths:
      - target\Three-in-a-Row.jar
