image: maven:latest

stages:
  - build

build:
  stage: build
  script:
    - mvn clean package
    - mvn checkstyle:checkstyle
    - java -jar target/project-8-1.0-SNAPSHOT.jar
  artifacts:
    paths:
      - target/project-8-1.0-SNAPSHOT.jar
